// All posts

get http://localhost:8000/api/posts
###
// Create new post
post http://localhost:8000/api/posts
Content-Type: application/json

{
  "title": "Post 02",
  "body": "This a content post"
}
###
// Get a post
get http://localhost:8000/api/posts/1
###
// Update a post
put http://localhost:8000/api/posts/2
Content-Type: application/json

{
  "title": "Post 02 updated",
  "body": "This a content post"
}
###
delete http://localhost:8000/api/posts/2
###
// Auth
post http://localhost:8000/api/register
Content-Type: application/json

{
  "name": "John",
  "email": "john3@gmail.com",
  "password": "12345",
  "passoword_confirmation": "12345"
}
###
post http://localhost:8000/api/login
###
post http://localhost:8000/api/logout
###



